export { SettingsPage } from "./SettingsPage";
export { ProductStandardsPage } from "./ProductStandardsPage";
export { ReprocessingPage } from "./ReprocessingPage";
export { AuthorizedUsersPage } from "./AuthorizedUsersPage";
export { AutoClosePage } from "./AutoClosePage";
export { ProductCatalogPage } from "./ProductCatalogPage";
export { DuplicatesPage } from "./DuplicatesPage";
export { ZendeskUsersPage } from "./ZendeskUsersPage";
export { ZendeskUserDetailPage } from "./ZendeskUserDetailPage";
